services:
  secondbrainbackend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.be
    environment:
       CLOUD_NAME_KEY: ${CLOUD_NAME_KEY}
       API_KEY: ${API_KEY}
       API_SECRET: ${API_SECRET}
       MONGO_URL: ${MONGO_URL}
       SERVER_PORT: ${SERVER_PORT}
       JWT_USER_SECRET: ${JWT_USER_SECRET}
    ports:
      - "3000:3000"