name: "Deploy second-brain-backend to auzre VM"
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: DockerLogin
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
           
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./docker/Dockerfile.be
                push: true
                tags: lomashchoudhary/second-brain:${{ github.sha }}

            - name : Deploy it to a VM and run using docker hub
              run: |
                echo "${{ secrets.PRIVATE_KEY }}" &> ~/ssh_key
                mkdir -p ~/.ssh
                cd ~/.ssh
                touch ~/.ssh/know_hosts
                echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/know_hosts
                chmod 700  ~/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key rootUserAzure@${{secrets.VM_IP}} << EOF
                sudo docker --version
                sudo docker pull lomashchoudhary/second-brain:${{ github.sha }}
                sudo docker stop second-brain-backend || true
                sudo docker rm second-brain-backend || true
                sudo docker run -d --name second-brain-backend \
                -e CLOUD_NAME_KEY=${{secrets.CLOUD_NAME_KEY}} \
                -e API_KEY=${{secrets.API_KEY}}\
                -e API_SECRET=${{secrets.API_SECRET}}\
                -e MONGO_URL=${{secrets.MONGO_URL}} \
                -e SERVER_PORT=${{secrets.SERVER_PORT}} \
                -e JWT_USER_SECRET=${{secrets.JWT_USER_SECRET}} \
                -p 3000:3000  \
                lomashchoudhary/second-brain:${{ github.sha }}
                EOF